### ISSUE TITLE
Crash when parsing malformed CXX file

### ISSUE THREAD

**Issue by retpoline** [CastXML/CastXML#210]
Hi folks,

A crash was found while fuzz testing of the castxml binary which can be triggered via a very short, malformed source file.

**crash.cxx**

```
;
```

**debug log**

```
$ LD_PRELOAD=/usr/lib/libefence.so CastXML/bin/castxml crash.cxx

  Electric Fence 2.2 Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>
Stack dump:
0.	Program arguments: CastXML/bin/castxml crash.cxx 
/usr/lib/llvm-10/lib/libLLVM-10.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1f)[0x7f74b5b1d4ff]
/usr/lib/llvm-10/lib/libLLVM-10.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x50)[0x7f74b5b1b7b0]
/usr/lib/llvm-10/lib/libLLVM-10.so.1(+0x981ac5)[0x7f74b5b1dac5]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f74b4dee210]
CastXML/bin/castxml(_ZN5clang6Parser24initializePragmaHandlersEv+0x4ef)[0x55afb581822f]
CastXML/bin/castxml(_ZN5clang6ParserC2ERNS_12PreprocessorERNS_4SemaEb+0x228)[0x55afb5793b98]
CastXML/bin/castxml(_ZN5clang8ParseASTERNS_4SemaEbb+0x6f)[0x55afb57931ef]
CastXML/bin/castxml(_ZN5clang14FrontendAction7ExecuteEv+0x48)[0x55afb54c38d8]
CastXML/bin/castxml(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x621)[0x55afb54730c1]
CastXML/bin/castxml(+0x594439)[0x55afb545e439]
CastXML/bin/castxml(+0x594d37)[0x55afb545ed37]
CastXML/bin/castxml(_Z8runClangPKPKcS2_RK7Options+0xc3a)[0x55afb545fb64]
CastXML/bin/castxml(main+0xeeb)[0x55afb54303e4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f74b4dcf0b3]
CastXML/bin/castxml(_start+0x2e)[0x55afb542f43e]
Segmentation fault (core dumped)

$ gdb CastXML/bin/castxml
Reading symbols from CastXML/bin/castxml...

(gdb) set environment LD_PRELOAD=/usr/lib/libefence.so

(gdb) r crashes/crash.cxx
Starting program: CastXML/bin/castxml crash.cxx

  Electric Fence 2.2 Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

  Electric Fence 2.2 Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>

Program received signal SIGSEGV, Segmentation fault.
0x0000555555ea222f in clang::Parser::initializePragmaHandlers() ()
(gdb) bt
#0  0x0000555555ea222f in clang::Parser::initializePragmaHandlers() ()
#1  0x0000555555e1db98 in clang::Parser::Parser(clang::Preprocessor&, clang::Sema&, bool) ()
#2  0x0000555555e1d1ef in clang::ParseAST(clang::Sema&, bool, bool) ()
#3  0x0000555555b4d8d8 in Execute () at /build/llvm-toolchain-10-yegZYJ/llvm-toolchain-10-10.0.0/clang/lib/Frontend/FrontendAction.cpp:936
#4  0x0000555555afd0c1 in ExecuteAction () at /build/llvm-toolchain-10-yegZYJ/llvm-toolchain-10-10.0.0/clang/lib/Frontend/CompilerInstance.cpp:965
#5  0x0000555555ae8439 in runClangCI(clang::CompilerInstance*, Options const&) ()
#6  0x0000555555ae8d37 in runClangImpl(char const* const*, char const* const*, Options const&) ()
#7  0x0000555555ae9b64 in runClang(char const* const*, char const* const*, Options const&) ()
#8  0x0000555555aba3e4 in main ()
```

**Comment by bradking** [comment]
I can't reproduce this locally.  How was your CastXML binary built?  It appears to be running against a system-installed LLVM/Clang 10.  The crash is occurring inside LLVM/Clang's `initializePragmaHandlers`, which is not code maintained here.

**Comment by retpoline** [comment]
Yes, it was built with Clang-- ah, I see that now and will follow up with Clang.

Thanks!
