### ISSUE TITLE
Missing namespace for template template parameter

### ISSUE THREAD

**Issue by PhilMarek** [CastXML/CastXML#61]
Hi.
Following code generates an incomplete output:
`namespace test {
class A { };
class B { };

template <class A, class B, template<class D, class E> class C>
class template_test { };

template <class D, class E> class
innerTemplate { };

class child : public template_test<A, B, innerTemplate> { };
}`

The corresponding xml entry to template_test has the attribute
`name="template_test&lt;test::A, test::B, innerTemplate&gt;"`
The namespace for innerTemplate is missing.

**Comment by bradking** [comment]
CastXML is printing the name that it gets from the Clang AST.  Unfortunately it looks like Clang exposes no API to customize this when printing type names (see discussion in #51).  One can see the same output in Clang diagnostic messages in cases like this.  Without a hook or customization option from Clang, this is not possible to fix.

For reference, here are some details.  Our `OutputRecordDecl` method calls the `getNameForDiagnostic` method on the Clang decl.  One can trace through the call stack below this to see what happens when it tries to print the `innerTemplate` template name:

```
#0  clang::NamedDecl::printName (this=0x66fa198, os=...) at /.../llvm/tools/clang/include/clang/AST/Decl.h:254
#1  0x000000000121dda5 in clang::operator<< (OS=..., ND=...) at /.../llvm/tools/clang/include/clang/AST/Decl.h:414
#2  0x00000000021462ba in clang::TemplateName::print (this=0x7fffffffc480, OS=..., Policy=..., SuppressNNS=false) at /.../llvm/tools/clang/lib/AST/TemplateName.cpp:181
#3  0x000000000214492f in clang::TemplateArgument::print (this=0x67004d0, Policy=..., Out=...) at /.../llvm/tools/clang/lib/AST/TemplateBase.cpp:385
#4  0x000000000216fb0a in clang::TemplateSpecializationType::PrintTemplateArgumentList (OS=..., Args=0x67004a0, NumArgs=3, Policy=..., SkipBrackets=false) at /.../llvm/tools/clang/lib/AST/TypePrinter.cpp:1458
#5  0x000000000201d472 in clang::ClassTemplateSpecializationDecl::getNameForDiagnostic (this=0x67003d8, OS=..., Policy=..., Qualified=false)
```

The `printName` method ends up just printing the name with no qualifiers.  In the case that qualifiers are written explicitly, e.g. `test::innerTemplate`, then `TemplateName::print` has a code path for `QualifiedTemplateName` that prints the qualifier as written.

**Comment by thewtex** [comment]
CC: @fbudin69500
